### ISSUE TITLE
🐛 fix: 회원가입 화면 스크롤 문제 

### ISSUE THREAD

**Issue by k-oyun** [WaitherTeam/Waither-FE#30]
# Title

- 회원가입 화면 키보드 입력 시 (회원가입 완료) 버튼 안보임

# TODO

- [ ] ScrollView 이용

# etc

- 해당 화면에 대해서 어떻게 처리할지 회의 후 결정

**Comment by yeopyeop-82** [comment]
KeyBoardAvoidingView 사용하면 됩니다 ! React Native 공식 docs에 명시되어 있는 기능이어서 편하게 사용하면 됩니다.
수요일날 만나서 설명 드릴게요 ~
